### ISSUE TITLE
Error saving to github

### ISSUE THREAD

**Issue by ppmnt** [jnetterf/hacklily#14]
Hi! I love the idea of hacklily, having a browser based IDE for sheet music creation is a great idea! However, whenever I try to save a file, I get this: 

![image](https://user-images.githubusercontent.com/75603007/101423334-a98cb280-38ad-11eb-9a76-3efb28f404a0.png)

Note that the very first time it did successfully create the sheet-music repository, so I know that authentication and permissions on github are working. I'm using Chrome on Windows 10. I suspected Chrome extensions to be the issue, but I tried in an incognito window without extensions and got the same error.

Please let me know if you have any suggestions! Thanks!

**Comment by efimi** [comment]
Thank you for this super usefull WebApp!

I have the same problem on my mac safing files on github:

I got this error message:
TypeError: e.sent.map is not a function. (In 'e.sent.map(e.t0)', 'e.sent.map' is undefined)
(Safari Browser)

**Comment by RazerMoon** [comment]
@jnetterf Please take a look at this.

## Why this happens:
This issue occurs when the javascript tries to access the "master" branch of your sheet music repo:

![1](https://user-images.githubusercontent.com/33849459/105631699-a5a9f500-5e47-11eb-819b-b2ca14d95b00.png)
![2](https://user-images.githubusercontent.com/33849459/105631731-cf631c00-5e47-11eb-8c8b-1871486f386a.png)

Even though the repo is created with the "main" branch instead of "master":

![4](https://user-images.githubusercontent.com/33849459/105631755-f1f53500-5e47-11eb-8e8c-8c0ebdbe3831.png)

## To fix this:

### Quick instructions:

Rename the "main" branch to "master".

### Detailed instructions:

![example](https://user-images.githubusercontent.com/33849459/105631990-fd952b80-5e48-11eb-92bc-956168cc1c54.gif)

1. Click on "branch"
2. Select the pencil icon to edit the name.
3. Change "main" to "master"

**You should now be able to save scores.**

**Comment by PaulMorris** [comment]
I also hit this error and didn't know how to resolve it.  Fortunately I happened to find this when looking through closed issues.  

I don't think this issue should be closed yet.  Github now uses "main" instead of "master" for the default branch on new repos (since October 1, 2020: https://www.infoq.com/news/2020/10/github-main-branch/), and that breaks the Github integration for new Hacklily users.

A potential fix: detect the default branch of the repo and then use that branch name, whether it is "main" for new users or "master" for older existing users.  For example, using the Github api: https://stackoverflow.com/a/16501903

**Comment by emilyskidsister** [comment]
Thank you for reporting, this should be resolved now.
